controllers_film:
  resource: ../src/UserInterface/Film/Http/Rest
  type: attribute

controllers_users:
  resource: ../src/UserInterface/User/Http/Rest
  type: attribute

api_login_check:
  path: /api/v1/login

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }